GET http://localhost:3000/users

###


POST http://localhost:3000/users
Content-Type: application/json


{
    "name": "ashish",
    "username": "aruna1",
    "password": "password2"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json


{
    "name": "aruna",
    "username": "aruna",
    "password": "password1"
}

###

POST http://localhost:3000/users/login
Content-Type: application/application/json

{
    "name": "Lavar",
    "password": "password"
}